name: Run Performance Test V2

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Endpoint to test'
        required: true
        default: 'clover-os-uat.lendingfront.com'
      name_test:
        description: 'File name .jmx to run'
        required: true
        default: 'originationservice_with_parameters.jmx'
      timeout:
        description: 'Timeout to fail test (Value in milliseconds)'
        required: true
        default: '10000'
      threads:
        description: 'Threads concurrent to run'
        required: true
        default: '1'
      loops:
        description: 'Number of times the test will run'
        required: true
        default: '1'
jobs:
  Run_Performance_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python
        run: echo "python"
      - name: Set up Python
        env:
          PYTHON_VERSION: 3.7
        uses: actions/setup-python@v2
        with:
          python-version: $PYTHON_VERSION
      - name: Install JMeter
        run: |
          python bin/JMeterInstaller.py
          rm -rf results && mkdir results
          chmod -R 777 ./
      - name: Run and Generate Report
        run: apache-jmeter-5.1/bin/jmeter.sh -j results/jmeter.log -p tests/user.properties -t tests/${{ github.event.inputs.name_test }} -n -l results/result.csv -Jserver=${{ github.event.inputs.url }} -Jtimeout=${{ github.event.inputs.timeout }} -Jthreads=${{ github.event.inputs.threads }} -JloopCount=${{ github.event.inputs.loops }}
      - name: Generate Report
        run: |
          rm -rf results/JMeterReport && mkdir results/JMeterReport
          apache-jmeter-5.1/bin/jmeter.sh -g results/result.csv -o results/JMeterReport
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: report-${{ github.event.inputs.name_test }}
          path: results/JMeterReport/
      - name: Run and Generate Report 2
        run: apache-jmeter-5.1/bin/jmeter.sh -j results/jmeter.log -p tests/user.properties -t tests/${{ github.event.inputs.name_test }} -n -l results/result.csv -Jserver=${{ github.event.inputs.url }} -Jtimeout=${{ github.event.inputs.timeout }} -Jthreads=${{ github.event.inputs.threads }} -JloopCount=${{ github.event.inputs.loops }}
      - name: Generate Report 2
        run: |
          rm -rf results/JMeterReport && mkdir results/JMeterReport
          apache-jmeter-5.1/bin/jmeter.sh -g results/result.csv -o results/JMeterReport
      - name: Upload Results 2
        uses: actions/upload-artifact@v2
        with:
          name: report-${{ github.event.inputs.name_test }}
          path: results/JMeterReport/